### ISSUE TITLE
h1 & h2 not really aligned center, though it is not overridden according to inspect, and despite !important being added for extra precaution

### ISSUE THREAD

**Issue by ChristerNilsson** [0iseaux/hyf-html-css#2]
https://github.com/0iseaux/hyf-html-css/blob/master/week2/index.html

It seems the sum of all your vw:s are more than 100%.
So, your window has to scroll sideways.
The text "grid" is centered correctly.
Make all vw:s half as a first approximation.
https://www.w3schools.com/cssref/css_units.asp

I will solve your other questions, when they are in separate issues.

**Comment by 0iseaux** [comment]
Thanks so much! will try it out.
For complete reference, here are the links: https://0iseaux.github.io/hyf-html-css/links.html

**Comment by ChristerNilsson** [comment]
Please fix this issue before continuing with the other issues. They might be related.

**Comment by ChristerNilsson** [comment]
If you think this is issue fixed, please close it.
