### ISSUE TITLE
The Github Pages link can only to point to one file!

### ISSUE THREAD

**Issue by ChristerNilsson** [0iseaux/hyf-html-css#3]
Define one page with links to all other index.html files in your repo.
Like I have done here: https://christernilsson.github.io/Lab/

**Comment by 0iseaux** [comment]
Here are the links: https://0iseaux.github.io/hyf-html-css/links.html

**Comment by ChristerNilsson** [comment]
Actually, I would like to see the resulting pages for three .html files. I have no problem looking at the source code using github itself. If you look at my link, Lab, you will see ONE repo, but hundreds if index.html.
https://christernilsson.github.io/Lab/ 

Please publish this file instead of the current file:
https://0iseaux.github.io/hyf-html-css/docs/links.html 

Also make sure the three .html files can be shown from this file.
And I do not mean the source code.
I want to see rendered pages.

**Comment by ChristerNilsson** [comment]
Good Job!
